#include "fir.h"

// Shift register – persists state across calls (one call per input sample)

// Low-pass FIR coefficients in Q15 (generated by fir_golden.py, scipy firwin,
// cutoff=0.04, Hamming window, symmetric 15-tap)
static const ap_int<16> coeff[NUM_TAPS] = {
    307, 500, 1038, 1839, 2750, 3586, 4173,
    4383,
    4173, 3586, 2750, 1839, 1038, 500, 307
};

void fir(hls::stream<packet>& in_s, hls::stream<packet>& out_s) {
    //  Specify AXI-Stream interface for both ports
    #pragma HLS INTERFACE axis port=in_s
    #pragma HLS INTERFACE axis port=out_s
    #pragma HLS PIPELINE II=1
    
    static ap_int<16> shift_reg[NUM_TAPS];
    
    // ##############
    // NOTE: Insert any function level pragmas if needed
    
    // Read one Q15 sample from the AXI-Stream input
    packet tmp = in_s.read();
    ap_int<16> x = (ap_int<16>)tmp.data;   // lower 16 bits, sign-extended

    // Shift register update (unrolled – combinational, no extra latency)
    SHIFT_LOOP: 
    for (int i = NUM_TAPS - 1; i > 0; i--) {
        // ##############
        // NOTE: Insert any pragmas here if needed
        // #pragma HLS UNROLL  // Duplicates the for loop body so that multiple instances of it can run in parallel

        shift_reg[i] = shift_reg[i - 1];
    }
    shift_reg[0] = x;

    ap_int<32> acc = 0;
    MAC_LOOP: 
    for (int i = 0; i < NUM_TAPS; i++) {
        // ##############
        // NOTE: Insert any pragmas here if needed
        // #pragma HLS UNROLL  // Duplicates the for loop body so that multiple instances of it can run in parallel
        
        ap_int<32> prod = coeff[i] * shift_reg[i];
        acc += prod;
    }

    // Scale Q30 back to Q15 (arithmetic right-shift by 15) and clamp to int16
    ap_int<32> y = (ap_int<32>)(acc >> 15);
    if (y >  32767) y =  32767;
    if (y < -32768) y = -32768;

    // Forward all side-channel signals; replace data with filtered output
    tmp.data = y;
    out_s.write(tmp);
}
